Bump github.com/mattermost/mattermost-server/v6 from 6.2.1 to 6.3.0 in /dependabot (#140)
* Bump github.com/mattermost/mattermost-server/v6 in /dependabot

Bumps [github.com/mattermost/mattermost-server/v6](https://github.com/mattermost/mattermost-server) from 6.2.1 to 6.3.0.
- [Release notes](https://github.com/mattermost/mattermost-server/releases)
- [Changelog](https://github.com/mattermost/mattermost-server/blob/master/CHANGELOG.md)
- [Commits](https://github.com/mattermost/mattermost-server/compare/v6.2.1...v6.3.0)

---
updated-dependencies:
- dependency-name: github.com/mattermost/mattermost-server/v6
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Add python2 dependency

Apparently something in 6.3.0 is using python2 for the first time?

* Use node v15 by default

We are now getting this error when building:

    /build/.node-gyp/16.13.2/include/node/v8-internal.h:492:38: error: 'remove_cv_t' is not a member of 'std'

which the internet suggests is a problem with node 16 and node-sass. According to https://stackoverflow.com/questions/67241196/error-no-template-named-remove-cv-t-in-namespace-std-did-you-mean-remove , supposedly newer versions of node-sass support node 16, and the other solution is to pass -std=c++14 instead of c++0x (which is what is being done right now), but I can't say for sure whether this build script will work with CXXFLAGS or not. The other fix would seem to be to update node-sass to a version that supports node16, but that would presumably be more patching of files, this time in mattermost-webapp, so I'm trying the least-invasive option first.

* Update release.mk patch

* Update how we retrieve the Mattermost version

With mmctl in the require list in the go.mod, mattermost-server no longer appears on the same line as the require statement, so splitting by spaces means we now need the second split entry instead of the third.

We could also fix this by removing mmctl from the go.mod, which I was going to do, but that means every Dependabot update would no longer work. So going forward we will need to ensure that the go.mod always has the mattermost-server require on its own line instead of inline with the require statement.

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: parnic-sks <chris@straykitestudios.com>